### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by judemont** [TheBigEye/Python-OS#26]
When I run OS.py I have this error : 

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "/home/judemont/autre/Python-OS/System/shell/Boot/Desktop/Desktop.py", line 51, in __init__
    Desktop.desktop_initializer(self)
  File "/home/judemont/autre/Python-OS/System/shell/Boot/Desktop/Desktop.py", line 73, in desktop_initializer
    self.master.configure(background = "#001023",cursor = XCursor_2)
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1702, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1692, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: bad cursor spec "@Assets/Cursors/Linux/XCursor-2.xbm"

```

**Comment by TheBigEye** [comment]
Tkinter tries to set a custom mouse cursor based on a bitmap (XBM), and fails. I think the desktop environment doesn't play well with tkinter
