### ISSUE TITLE
Browser doesn't work

### ISSUE THREAD

**Issue by PartehDev** [TheBigEye/Python-OS#27]
Whenever I use the "web browser" I get this error:
`K:\Python-OS>python os.py
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "K:\Python-OS\System\shell\Boot\Bootloader.py", line 66, in update_os_loader
    self.loading.configure(image=frame)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!label4"
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1921, in __call__
    return self.func(*args)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 839, in callit
    func(*args)
  File "K:\Python-OS\System\shell\Boot\Bootloader.py", line 38, in update_vmw_loader
    self.loader_bar.configure(width=ind)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1675, in configure
    return self._configure('configure', cnf, kw)
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python310\lib\tkinter\__init__.py", line 1665, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!label2"`...

**Comment by CerebralSeed** [comment]
I'm having a similar issue with the OS crashing upon opening the browser.

**Comment by WinFan3672** [comment]
This is an issue with Tkinterweb, the python module that runs the web browser. A fix would be to use requests to download the web page and use a HTML rendering library to render the downloaded page.
